### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by janbro** [notatestuser/gift#96] opened 2017-07-11 19:35 UTC
This is happening when I pass "HEAD" and a merge commits hash to the diff function.

```
ref5 = /^index\s([0-9A-Fa-f]+)\.\.([0-9A-Fa-f]+)\s?(.+)?$/.exec(lines.shift()), m = ref5[0], a_blob = ref5[1], b_blob = ref5[2], b_mode = ref5[3];
                                                                                                ^

TypeError: Cannot read property '0' of null
    at Function.module.exports.Diff.parse (/Users/[redacted]/Documents/[redacted]/node_modules/gift/lib/diff.js:81:97)
    at /Users/[redacted]/Documents/[redacted/node_modules/gift/lib/repo.js:170:39
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)```

**Comment by PeterDaveHello** [comment] 2017-11-01 15:13
Same problem here.

**Comment by notatestuser** [comment] 2017-11-01 19:09
It might just be a case of that regex having to catch "HEAD" too. Could you try that and let me know if it resolves the problem?

**Comment by PeterDaveHello** [comment] 2017-11-01 19:51
for me, I don't know what's the problem yet but I got that problem on this repo: github.com/mervick/emojionearea, jut FYI

**Comment by MichalW** [comment] 2017-11-04 15:31
Same problem here:
```
ref1 = /^.+? (.*) (\d+) .*$/.exec(line), m = ref1[0], actor = ref1[1], epoch = ref1[2];
TypeError: Cannot read property '0' of null
at Function.module.exports.Commit.actor (.npm/package/node_modules/gift/lib/commit.js:176:56)
at Function.module.exports.Commit.parse_commits (.npm/package/node_modules/gift/lib/commit.js:139:21)
at .npm/package/node_modules/gift/lib/commit.js:99:39
at ChildProcess.exithandler (child_process.js:191:7)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:862:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
```

**Comment by notatestuser** [comment] 2017-11-05 10:42
If you guys could have a look into what the problem is here a pull request to fix it would be appreciated.

**Comment by PeterDaveHello** [comment] 2017-11-05 19:54
All I currently know is the problem appears with https://github.com/mervick/emojionearea, but I didn't know what's the problem to cause it yet, only some repos got this problem very recently, not sure if GitHub or git did anything.

**Comment by notatestuser** [comment] 2017-11-06 02:27
@janbro @MichalW @PeterDaveHello which versions of git are you using?

**Comment by PeterDaveHello** [comment] 2017-11-06 08:24
@notatestuser I use git v2.7.4 and v2.14, same problem.

btw, I found the problem also exists with https://github.com/zabuto/calendar (and slowly increasing on different repository)

**Comment by MRWS** [comment] 2017-11-06 09:33
Got the same problem with https://github.com/shinnn/gulp-gh-pages/ on git v2.13.5

**Comment by MichalW** [comment] 2017-11-06 09:40
I have the impression that the problem occurs only with github (not bitbucket)
my git version: `v2.11.0`

**Comment by PeterDaveHello** [comment] 2017-11-06 11:58
Okay I noticed that the commit id/hash test is not reliable, PR #98 sent!

**Comment by PeterDaveHello** [comment] 2017-11-06 12:13
#98 merged! Anyone wants to help test it? (Or even help review some related code!)

**Comment by notatestuser** [comment] 2017-11-06 12:35
Guys, please have a quick test with the problematic repositories mentioned above and I'll get this published. I don't want to break anyone's project!

**Comment by brecke** [comment] 2017-11-06 12:35
The fix worked for me!

**Comment by PeterDaveHello** [comment] 2017-11-06 12:38
@notatestuser give me few more mins to test :)

**Comment by notatestuser** [comment] 2017-11-06 13:10
Ran through some tests myself. Published in v0.10.1.

**Closed** 2017-11-06 13:11 UTC

**Comment by shockwave22** [comment] 2018-02-18 02:12
Found the fix to this error!
1> After you install gulp-gh-pages using npm, navigate to the below folder

node_modules\gulp-gh-pages\node_modules

2> delete gift folder under gulp-gh-pages

3> npm install gift

**Comment by notatestuser** [comment] 2018-02-18 10:36
Yes, the author of gulp-gh-pages to update gift to resolve shinnn/gulp-gh-pages#116 and shinnn/gulp-gh-pages#117.

**Comment by mryellow** [comment] 2019-07-07 23:53
`gulp-gh-pages doesn't support gulp <= v3.x. Update your project to use gulp >= v4.0.0.`

Is this patched for a Gulp3 version of `gulp-gh-pages`? Not wishing to ever "upgrade" to Gulp4.

**Comment by flipsasser** [comment] 2020-06-01 23:56
For anyone still having this problem who happens to also be using Yarn, I added a field to "resolutions" in `package.json` to ensure the right version of Gift wins when running `yarn install`:

In my `package.json` file I added:

```json
{
  ...other package.json stuff...,
  "resolutions": {
    "gift": "^0.10.2"
  }
}
```

This solved the problem for me.

**Comment by pratha-solutelabs** [comment] 2022-12-20 18:09
> Same problem here:
> 
> ```
> ref1 = /^.+? (.*) (\d+) .*$/.exec(line), m = ref1[0], actor = ref1[1], epoch = ref1[2];
> 
> TypeError: Cannot read property '0' of null
> at Function.module.exports.Commit.actor (.npm/package/node_modules/gift/lib/commit.js:176:56)
> at Function.module.exports.Commit.parse_commits (.npm/package/node_modules/gift/lib/commit.js:139:21)
> at .npm/package/node_modules/gift/lib/commit.js:99:39
> at ChildProcess.exithandler (child_process.js:191:7)
> at emitTwo (events.js:87:13)
> at ChildProcess.emit (events.js:172:7)
> at maybeClose (internal/child_process.js:862:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
> ```

I have received same issue right now. Can anyone tell me how do i fix it? @MichalW what solution worked for you?
